### ISSUE TITLE
Créer un Wordpress à côté

### ISSUE THREAD

**Issue by mathieu-mc** [ezseed/ezseed#44]
Bonjour,

Je tiens tout d'abord à félicité le travaille effectué pour Ezseed !

Voilà mon problème , j'ai voulu mettre en place un Wordpress mais je n'ai pas réussi car j'ai un message d'erreur : Cannot GET /wordpress

Pouvez vous m'aider SVP

cordialement

**Comment by soyuka** [comment]
via #46
