### ISSUE TITLE
File path in download is wrong

### ISSUE THREAD

**Issue by LucasAdam** [ezseed/ezseed#46]
I instaled ezseed (from this git) on /ezseed but somehow when i try to stream or download a movie the path is incorrect.

It's like "xx.xxx.xxx.xx/movies/54b3bd8eb192a1dd7a4dd2ef/download"
Instead of  "xx.xxx.xxx.xx/ezseed/movies/54b3bd8eb192a1dd7a4dd2ef/download"

How could I fix that ?

**Comment by soyuka** [comment]
Hi,

Could you give me the output of the `~/.ezseed/config.js` and the `/etc/nginx/sites-enabled/ezseed` files please?

**Comment by LucasAdam** [comment]
Here is the config.js

http://pastebin.com/mBnGRMYG

And the nginx ezseed

http://pastebin.com/giLKXHUy

Everything is working fine so far except the download/stream

**Comment by soyuka** [comment]
Thanks, this seems to be perfectly working, I missed a leading `/` in https://github.com/ezseed/web/blob/master/partials/items/movie.html#L52.

I'll fix this this evening and let you know! Thanks!

**Comment by LucasAdam** [comment]
Alright ! Thanks to you :+1:

**Comment by soyuka** [comment]
I'll be delayed, found another issue with sockets, I'll publish tomorrow ;)

**Comment by soyuka** [comment]
Should be fixed, `npm update ezseed -g` to update.

**Comment by LucasAdam** [comment]
Looks like i have an issue 

npm ERR! ezseed@0.6.10 install: `EZSEED_ENV=install ./bin/ezseed`
npm ERR! Exit status 126
npm ERR!
npm ERR! Failed at the ezseed@0.6.10 install script.
npm ERR! This is most likely a problem with the ezseed package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     EZSEED_ENV=install ./bin/ezseed
npm ERR! You can get their info via:
npm ERR!     npm owner ls ezseed
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.2.0-4-amd64
npm ERR! command "/root/.nvm/v0.10.32/bin/node" "/root/.nvm/v0.10.32/bin/npm" "update" "ezseed" "-g"
npm ERR! cwd /root
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0

**Comment by soyuka** [comment]
You're using root, please add the `--unsafe-perm` argument :)

**Comment by LucasAdam** [comment]
Just did that, look what happens now 
http://puu.sh/esoHP/abb1c1f48e.png

**Comment by soyuka** [comment]
Try restarting ezseed:
```
ezseed restart
```

(Note to myself)
Small mistake in https://github.com/ezseed/web/blob/master/index.js#L21

**Comment by LucasAdam** [comment]
Huh.... Looks like it fuckeds things up
-bash: ezseed: command not found

**Comment by soyuka** [comment]
I just updated on my own server with no issues. I think that the first `npm update` broke your installation.

No worries, just launch `npm i ezseed -g --unsafe-perm`.
